[common.consensus_config]
peers_timeout = 10000
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.consensus_config.timeout_adjuster]
timeout = 500
type = "Constant"

[common.services_config]

[node]
addr = "127.0.0.1:6002"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "f046a4a382fae0ffa045073fbcba995d008eef47b5780af6a1782714f6b28e27"
service_key = "c5167a1edaecb0dc60e643e35e42b45852e51448ee7867a2cfad21f2548cc139"
