[common.consensus_config]
peers_timeout = 10000
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.consensus_config.timeout_adjuster]
timeout = 500
type = "Constant"

[common.services_config]

[node]
addr = "127.0.0.1:6001"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "ecf88e4248a678ac0cc7ecc780f91340f71fdf055d55dc45e5ae2f8971f54bc8"
service_key = "90840bbb6ed312e61593a8676269d16b14428b9b068596176889f715c3b4bbdb"
